-- VocabMaster NIDA — Vocabulary Expansion (~300 คำ)
-- ครอบคลุม A1-C2, ทุก category, โฟกัส NIDA TAS domains:
--   Public Administration, Economics, Social Sciences, Law, Research Methods
-- ON CONFLICT (word) DO NOTHING — ปลอดภัย สามารถรันซ้ำได้

INSERT INTO words (word, definition, thai_meaning, example_sentence, part_of_speech, level, category, frequency) VALUES

-- =====================================================================
-- A1 — GENERAL (35 คำ)  พื้นฐาน Placement Test
-- =====================================================================
('achieve','to successfully accomplish a goal','บรรลุเป้าหมาย','Students must achieve a B2 level to enter the program.','verb','A1','general',95),
('benefit','an advantage gained from something','ประโยชน์','The benefit of regular study is improved retention.','noun','A1','general',93),
('cause','the reason something happens','สาเหตุ','Poverty is a major cause of social inequality.','noun','A1','general',92),
('challenge','a difficult task that requires effort','ความท้าทาย','Climate change is a major challenge for all nations.','noun','A1','general',90),
('choose','to select one option from several','เลือก','Citizens choose their leaders through elections.','verb','A1','general',88),
('create','to make something new','สร้าง','The government aims to create more jobs.','verb','A1','general',92),
('describe','to give details about something','บรรยาย','Please describe the main features of the policy.','verb','A1','general',88),
('develop','to grow or improve over time','พัฒนา','Countries must develop their human capital.','verb','A1','general',94),
('discuss','to talk about a topic in detail','อภิปราย','We will discuss the results in the next section.','verb','A1','general',87),
('effect','a change resulting from an action','ผลกระทบ','The effect of the new policy was immediate.','noun','A1','general',92),
('effort','hard work toward a goal','ความพยายาม','Sustained effort is required to master a language.','noun','A1','general',88),
('explain','to make something clear','อธิบาย','The report explains the causes of inflation.','verb','A1','general',91),
('focus','to concentrate on something','มุ่งเน้น','The study focuses on urban poverty.','verb','A1','general',89),
('grow','to increase in size or amount','เติบโต','The economy grew by three percent last year.','verb','A1','general',90),
('improve','to make something better','ปรับปรุง','The project aims to improve public services.','verb','A1','general',93),
('include','to have something as part of a whole','รวมถึง','The report includes recommendations for reform.','verb','A1','general',92),
('increase','to become larger in number or amount','เพิ่มขึ้น','Tax revenues increased significantly this year.','verb','A1','general',93),
('lead','to guide or be in charge of','นำ','Strong leadership can lead a country to prosperity.','verb','A1','general',91),
('need','to require something essential','ต้องการ','Communities need access to clean water.','verb','A1','general',95),
('plan','a set of actions to achieve a goal','แผนงาน','The development plan covers five years.','noun','A1','general',90),
('provide','to supply or make something available','จัดหา','The government provides healthcare to all citizens.','verb','A1','general',92),
('reduce','to make something smaller or less','ลด','The policy aims to reduce carbon emissions.','verb','A1','general',91),
('result','something that happens because of an action','ผลลัพธ์','The result of the study showed significant improvement.','noun','A1','general',92),
('show','to demonstrate or make something visible','แสดงให้เห็น','The data shows a downward trend in crime.','verb','A1','general',90),
('solve','to find an answer to a problem','แก้ไขปัญหา','Governments must solve the housing crisis.','verb','A1','general',88),
('support','to help or back something up','สนับสนุน','Community support is essential for local development.','verb','A1','general',91),
('understand','to know the meaning of something','เข้าใจ','Citizens must understand their rights.','verb','A1','general',93),
('local','relating to a particular area or community','ท้องถิ่น','Local government handles community services.','adjective','A1','general',90),
('national','relating to a whole country','ระดับชาติ','National policies affect all citizens equally.','adjective','A1','general',92),
('public','available to or shared by all people','สาธารณะ','Public health is a government responsibility.','adjective','A1','general',91),
('report','an official account of findings','รายงาน','The annual report outlines government spending.','noun','A1','general',89),
('standard','a level of quality used as a measure','มาตรฐาน','Educational standards must be maintained.','noun','A1','general',88),
('access','the ability to use or reach something','การเข้าถึง','Equal access to education reduces inequality.','noun','A1','general',90),
('issue','an important topic or problem','ประเด็น','Corruption remains a critical issue in the region.','noun','A1','general',87),
('section','a distinct part of something larger','ส่วน','The final section covers policy recommendations.','noun','A1','general',85),

-- =====================================================================
-- A2 — ACADEMIC (30 คำ)
-- =====================================================================
('advantage','a condition giving a superior position','ข้อได้เปรียบ','One advantage of online learning is flexibility.','noun','A2','academic',85),
('analysis','detailed examination to understand something','การวิเคราะห์','A thorough analysis of the data is required.','noun','A2','academic',88),
('apply','to put a method or principle into practice','นำไปใช้','These principles can be applied in real settings.','verb','A2','academic',85),
('argument','a reason given to support or oppose an idea','ข้อโต้แย้ง','The author presents a convincing argument for reform.','noun','A2','academic',82),
('aspect','a particular feature or part of something','ด้าน','This aspect of the policy needs further review.','noun','A2','academic',84),
('approach','a way of dealing with or studying something','แนวทาง','A new approach is needed to address inequality.','noun','A2','academic',86),
('conclusion','a judgment reached after consideration','บทสรุป','The conclusion summarizes the key findings.','noun','A2','academic',85),
('contribute','to give something toward a common goal','มีส่วนร่วม','Education contributes to economic development.','verb','A2','academic',83),
('data','facts and statistics collected for analysis','ข้อมูล','The data suggests a clear correlation.','noun','A2','academic',90),
('decrease','to become or make smaller in amount','ลดลง','Crime rates decreased following the new policy.','verb','A2','academic',85),
('effective','producing the intended or desired result','มีประสิทธิผล','An effective policy addresses root causes.','adjective','A2','academic',86),
('element','an important or essential part of something','องค์ประกอบ','Trust is a key element of good governance.','noun','A2','academic',84),
('establish','to set up or prove firmly','ก่อตั้ง','The committee was established to review the law.','verb','A2','academic',83),
('evidence','information showing whether something is true','หลักฐาน','Strong evidence supports this hypothesis.','noun','A2','academic',87),
('examine','to inspect or consider carefully','ตรวจสอบ','Researchers examined the long-term effects.','verb','A2','academic',82),
('experience','knowledge or skill gained from doing things','ประสบการณ์','Work experience is valued by employers.','noun','A2','academic',88),
('function','the purpose or role of something','หน้าที่','The function of this institution is regulatory.','noun','A2','academic',85),
('influence','to have an effect on someone or something','อิทธิพล','Media can influence public opinion significantly.','noun','A2','academic',86),
('investigate','to examine a problem or situation carefully','สืบสวน','The commission will investigate the allegations.','verb','A2','academic',82),
('knowledge','understanding of a subject or skill','ความรู้','Knowledge transfer is vital for development.','noun','A2','academic',89),
('method','a way of doing something systematically','วิธีการ','The method used must be clearly documented.','noun','A2','academic',87),
('purpose','the reason for which something is done','จุดประสงค์','The purpose of the study is to identify barriers.','noun','A2','academic',86),
('research','systematic study to establish facts','การวิจัย','Research shows that early intervention is effective.','noun','A2','academic',88),
('role','the function someone or something has','บทบาท','Civil society plays an important role in democracy.','noun','A2','academic',86),
('source','a place or person providing something','แหล่งที่มา','The source of the data must be verified.','noun','A2','academic',85),
('theory','an idea used to explain observed facts','ทฤษฎี','The theory has been tested in several contexts.','noun','A2','academic',84),
('characteristic','a typical feature of something','ลักษณะเฉพาะ','One characteristic of good governance is transparency.','noun','A2','academic',83),
('identify','to recognize and name something precisely','ระบุ','Researchers identified three key variables.','verb','A2','academic',86),
('respond','to say or act in reply to something','ตอบสนอง','Governments must respond quickly to crises.','verb','A2','academic',82),
('outcome','the final result of a process or action','ผลลัพธ์สุดท้าย','The outcome of the negotiation was a new treaty.','noun','A2','academic',84),

-- A2 — GENERAL (10 คำ)
('area','a region or part of a country','พื้นที่','The rural area lacks access to basic services.','noun','A2','general',88),
('central','most important or main','สำคัญที่สุด','Education is central to human development.','adjective','A2','general',86),
('economic','relating to the economy or finances','ทางเศรษฐกิจ','Economic growth must be inclusive to reduce poverty.','adjective','A2','general',87),
('political','relating to government and public affairs','ทางการเมือง','Political stability attracts foreign investment.','adjective','A2','general',87),
('social','relating to society and its organization','ทางสังคม','Social inequality remains a challenge in Thailand.','adjective','A2','general',87),
('traditional','following established customs over time','แบบดั้งเดิม','Traditional values influence policy decisions.','adjective','A2','general',82),
('urban','relating to a city or town','ในเมือง','Urban migration is accelerating in Southeast Asia.','adjective','A2','general',84),
('cultural','relating to culture and society','ทางวัฒนธรรม','Cultural diversity enriches a nation.','adjective','A2','general',83),
('financial','relating to money and finances','ทางการเงิน','Financial stability is necessary for development.','adjective','A2','general',86),
('environmental','relating to the natural world around us','ด้านสิ่งแวดล้อม','Environmental protection is a shared responsibility.','adjective','A2','general',85),

-- =====================================================================
-- B1 — ACADEMIC (30 คำ)
-- =====================================================================
('allocate','to distribute resources for a specific purpose','จัดสรร','The government allocated funds to rural development.','verb','B1','academic',75),
('alternative','another possible choice or course of action','ทางเลือก','An alternative approach may be more effective.','noun','B1','academic',78),
('anticipate','to expect or predict something before it happens','คาดการณ์','Researchers anticipate a significant rise in demand.','verb','B1','academic',72),
('clarify','to make something easier to understand','ชี้แจง','The minister clarified the government position.','verb','B1','academic',74),
('component','a part of a larger system or structure','ส่วนประกอบ','Trust is a key component of social capital.','noun','B1','academic',77),
('consequence','a result or effect of an action or condition','ผลที่ตามมา','The consequence of poor governance is inequality.','noun','B1','academic',78),
('derive','to obtain something from a source','ได้รับมาจาก','These principles were derived from classical theory.','verb','B1','academic',72),
('expand','to increase in size, scope, or importance','ขยาย','The program was expanded to include rural areas.','verb','B1','academic',77),
('explicit','clearly stated and leaving no room for doubt','ชัดเจนโดยตรง','The policy sets explicit targets for each sector.','adjective','B1','academic',74),
('formulate','to create a plan or idea in a systematic way','กำหนดขึ้นอย่างเป็นระบบ','Officials formulated a new strategy for growth.','verb','B1','academic',71),
('generate','to produce or create something','ก่อให้เกิด','The project will generate over one thousand jobs.','verb','B1','academic',78),
('imply','to suggest something without stating it directly','บอกเป็นนัย','The findings imply a need for policy reform.','verb','B1','academic',73),
('maintain','to keep something in good condition over time','รักษา','It is difficult to maintain standards without funding.','verb','B1','academic',78),
('pursue','to follow or try to achieve something','ดำเนินตาม','The administration pursues an inclusive growth agenda.','verb','B1','academic',74),
('refine','to improve something by making small changes','ปรับปรุงให้ดีขึ้น','The model was refined based on stakeholder feedback.','verb','B1','academic',71),
('reinforce','to strengthen or support something further','เสริมสร้าง','The results reinforce earlier findings.','verb','B1','academic',74),
('restrict','to limit or keep within certain boundaries','จำกัด','Access to classified data is restricted to officials.','verb','B1','academic',72),
('specify','to state something in a clear and exact way','ระบุอย่างชัดเจน','The guidelines specify the required format.','verb','B1','academic',73),
('summarize','to give a brief account of the main points','สรุปใจความ','The abstract summarizes the key findings.','verb','B1','academic',75),
('sustain','to keep something going over a long period','รักษาไว้ยาวนาน','Economic growth must be sustained for decades.','verb','B1','academic',77),
('valid','based on sound reasoning or solid evidence','ถูกต้องตามหลัก','A valid argument must be supported by evidence.','adjective','B1','academic',76),
('verify','to confirm that something is true or accurate','ตรวจสอบยืนยัน','Researchers verified the data before publishing.','verb','B1','academic',74),
('adequate','enough for what is required','เพียงพอ','Adequate funding is needed for the program to succeed.','adjective','B1','academic',75),
('apparent','clearly visible or obvious','เห็นได้ชัด','There is an apparent lack of interagency coordination.','adjective','B1','academic',73),
('appropriate','suitable for a particular situation','เหมาะสม','The response must be appropriate to the context.','adjective','B1','academic',80),
('capable','having the ability or skill to do something','มีความสามารถ','The team is capable of delivering results on time.','adjective','B1','academic',78),
('essential','absolutely necessary for a purpose','จำเป็นอย่างยิ่ง','Community participation is essential for sustainability.','adjective','B1','academic',80),
('propose','to put forward a plan or idea for consideration','เสนอ','The committee proposed a series of structural reforms.','verb','B1','academic',77),
('retain','to continue to have or keep something','รักษาไว้','It is important to retain skilled workers in the public sector.','verb','B1','academic',73),
('revise','to change or improve something after review','แก้ไข','The policy was revised following public consultation.','verb','B1','academic',74),

-- B1 — BUSINESS (15 คำ)
('administration','the process of organizing and managing a system','การบริหาร','Effective administration reduces bureaucratic waste.','noun','B1','business',85),
('budget','a financial plan for a set period','งบประมาณ','The annual budget allocates funds to each ministry.','noun','B1','business',84),
('compete','to try to be more successful than others','แข่งขัน','Countries compete for foreign direct investment.','verb','B1','business',80),
('consumer','a person who buys goods or services','ผู้บริโภค','Consumer confidence affects overall economic growth.','noun','B1','business',83),
('demand','the desire or need for a product or service','ความต้องการ','Demand for skilled workers has increased significantly.','noun','B1','business',84),
('employ','to give paid work to someone','จ้างงาน','The public sector employs over two million people.','verb','B1','business',82),
('enterprise','a business or commercial organization','กิจการ','Small enterprises drive local economic growth.','noun','B1','business',78),
('investment','money put into something to earn a return','การลงทุน','Foreign investment is vital for national development.','noun','B1','business',85),
('manage','to be in charge of running something','จัดการ','The ability to manage resources effectively is essential.','verb','B1','business',84),
('market','the activity of buying and selling goods','ตลาด','The labor market has changed significantly in recent years.','noun','B1','business',86),
('output','the amount produced by a person or system','ผลผลิต','GDP measures the total economic output of a country.','noun','B1','business',80),
('profit','money gained after deducting costs','กำไร','Public institutions should prioritize service over profit.','noun','B1','business',82),
('resource','a supply of something useful or valuable','ทรัพยากร','Natural resources must be used sustainably.','noun','B1','business',83),
('sector','a distinct part of an economy or society','ภาคส่วน','The public sector provides essential services to citizens.','noun','B1','business',81),
('revenue','income generated from business or taxes','รายได้','Tax revenue funds public infrastructure and services.','noun','B1','business',82),

-- B1 — SOCIAL (10 คำ)
('community','a group of people living in the same area','ชุมชน','Community engagement is vital for local development.','noun','B1','social',85),
('culture','the beliefs and customs of a particular group','วัฒนธรรม','Cultural understanding promotes social cohesion.','noun','B1','social',86),
('equality','the state of being treated the same as others','ความเท่าเทียม','Gender equality is a key sustainable development goal.','noun','B1','social',82),
('gender','the social characteristics of males and females','เพศสภาพ','Gender inequality limits economic participation.','noun','B1','social',80),
('poverty','the state of lacking basic necessities','ความยากจน','Poverty alleviation requires a multi-sector approach.','noun','B1','social',83),
('population','all the people living in a particular place','ประชากร','Rapid population growth strains public resources.','noun','B1','social',85),
('society','people as a whole living in an organized community','สังคม','Civil society plays a crucial role in democracy.','noun','B1','social',87),
('welfare','the health, comfort, and happiness of people','สวัสดิการ','Social welfare programs support vulnerable groups.','noun','B1','social',82),
('minority','a group that differs from the larger population','ชนกลุ่มน้อย','Minority rights must be protected under the law.','noun','B1','social',78),
('migrate','to move from one place to another to settle','อพยพ','Millions migrate to cities in search of employment.','verb','B1','social',76),

-- B1 — SCIENCE (10 คำ)
('experiment','a scientific procedure used to test a hypothesis','การทดลอง','The experiment was conducted under controlled conditions.','noun','B1','science',80),
('laboratory','a room or building used for scientific research','ห้องปฏิบัติการ','Data was collected in the laboratory over six months.','noun','B1','science',78),
('measure','to find the size, amount, or degree of something','วัด','We measured the impact of the intervention.','verb','B1','science',82),
('observe','to watch something carefully for information','สังเกต','Researchers observed behavioral changes in the study group.','verb','B1','science',80),
('percentage','a proportion expressed as a fraction of 100','ร้อยละ','A high percentage of students passed the exam.','noun','B1','science',83),
('predict','to say what will happen in the future','ทำนาย','Models can predict economic growth with reasonable accuracy.','verb','B1','science',79),
('sample','a small part representing the whole group','ตัวอย่าง','A random sample of five hundred respondents was selected.','noun','B1','science',82),
('statistic','a fact expressed as a number from data','สถิติ','This statistic reveals a sharp rise in unemployment.','noun','B1','science',81),
('survey','a study of opinions or data from a group','การสำรวจ','A national survey was conducted on living standards.','noun','B1','science',80),
('variable','a factor that can change in an experiment','ตัวแปร','The key variable in this study is household income level.','noun','B1','science',79),

-- =====================================================================
-- B2 — BUSINESS / GOVERNANCE (25 คำ) — NIDA Core Domain
-- =====================================================================
('accountability','the obligation to accept responsibility for actions','ความรับผิดชอบ','Accountability is a cornerstone of good governance.','noun','B2','business',78),
('audit','an official examination of accounts or processes','การตรวจสอบ','An independent audit revealed serious financial irregularities.','noun','B2','business',75),
('bureaucracy','a system with many complex rules and processes','ระบบราชการ','Excessive bureaucracy slows down service delivery.','noun','B2','business',73),
('compliance','acting in accordance with rules and regulations','การปฏิบัติตามกฎ','Compliance with anti-corruption laws is mandatory.','noun','B2','business',76),
('decentralization','transferring authority to local levels of government','การกระจายอำนาจ','Decentralization empowers local governments to serve communities.','noun','B2','business',70),
('deficit','when expenditures exceed revenues in a budget','การขาดดุล','The fiscal deficit widened due to increased social spending.','noun','B2','business',74),
('efficiency','achieving maximum output with minimum waste','ประสิทธิภาพ','Efficiency in public spending improves service delivery.','noun','B2','business',78),
('fiscal','relating to government finance and taxation','ทางการคลัง','Fiscal policy is used to manage economic cycles.','adjective','B2','business',72),
('governance','the way an organization or country is managed','การบริหารจัดการ','Good governance requires transparency and accountability.','noun','B2','business',78),
('incentive','something that encourages a particular behavior','สิ่งจูงใจ','Tax incentives attract investment to rural areas.','noun','B2','business',75),
('inflation','a sustained rise in the general price level','เงินเฟ้อ','High inflation erodes purchasing power of citizens.','noun','B2','business',76),
('mandate','an official instruction or authority to act','อำนาจหน้าที่','The agency has a mandate to regulate financial markets.','noun','B2','business',73),
('monetary','relating to money, currency, and financial systems','ทางการเงิน','Monetary policy controls interest rates and money supply.','adjective','B2','business',74),
('municipality','a city or town with its own local government','เทศบาล','The municipality is responsible for waste management.','noun','B2','business',71),
('partnership','a cooperative relationship between organizations','ความร่วมมือ','Public-private partnership can fund infrastructure projects.','noun','B2','business',76),
('performance','how well a system, person, or organization works','ผลการดำเนินงาน','Performance indicators measure public service quality.','noun','B2','business',78),
('procurement','the official process of obtaining goods or services','การจัดซื้อจัดจ้าง','Transparent procurement reduces corruption risks.','noun','B2','business',71),
('productivity','the rate at which work is done efficiently','ผลิตภาพ','Higher productivity leads to sustainable economic growth.','noun','B2','business',77),
('regulation','a rule made and enforced by authority','กฎระเบียบ','Environmental regulations protect natural resources.','noun','B2','business',77),
('stakeholder','anyone with an interest in a project or outcome','ผู้มีส่วนได้เสีย','All stakeholders must be consulted during policy design.','noun','B2','business',76),
('strategic','relating to a long-term plan to achieve goals','เชิงยุทธศาสตร์','Strategic planning is essential for national development.','adjective','B2','business',77),
('sustainability','the ability to maintain something over the long term','ความยั่งยืน','Environmental sustainability is a global priority.','noun','B2','business',78),
('transparency','operating openly so everyone can see what is done','ความโปร่งใส','Transparency in government builds public trust.','noun','B2','business',77),
('viable','capable of working successfully in practice','เป็นไปได้','A viable solution must be both effective and affordable.','adjective','B2','business',73),
('coordination','organizing different activities to work together','การประสานงาน','Interagency coordination is key to effective disaster response.','noun','B2','business',74),

-- B2 — SOCIAL (20 คำ)
('demographic','relating to the structure and statistics of a population','เกี่ยวกับประชากรศาสตร์','Demographic change affects retirement and healthcare systems.','adjective','B2','social',72),
('discrimination','treating someone unfairly based on a characteristic','การเลือกปฏิบัติ','Discrimination in the workplace is prohibited by law.','noun','B2','social',74),
('disparity','a large difference between two things','ความเหลื่อมล้ำ','Income disparity is a major concern in developing nations.','noun','B2','social',71),
('diversity','a range of many different people or things','ความหลากหลาย','Workforce diversity leads to greater innovation.','noun','B2','social',74),
('ethnicity','membership in a group sharing culture or origin','ชาติพันธุ์','Ethnicity can influence access to resources and opportunities.','noun','B2','social',70),
('inequality','unfair differences in wealth, opportunity, or treatment','ความไม่เท่าเทียม','Social inequality undermines democratic participation.','noun','B2','social',73),
('marginalized','treated as unimportant or excluded from society','ถูกกีดกัน','Marginalized groups often lack access to legal protection.','adjective','B2','social',68),
('migration','movement of people from one place to another','การอพยพ','Urban migration increases pressure on city infrastructure.','noun','B2','social',72),
('multiculturalism','the coexistence and respect for many different cultures','พหุวัฒนธรรมนิยม','Multiculturalism requires mutual respect and understanding.','noun','B2','social',67),
('prejudice','an unfair opinion formed without full knowledge','อคติ','Prejudice in hiring practices reduces workforce diversity.','noun','B2','social',71),
('privilege','a special advantage available only to some groups','สิทธิพิเศษ','Acknowledging privilege is a first step toward equity.','noun','B2','social',70),
('refugee','a person forced to leave their country for safety','ผู้ลี้ภัย','Refugee resettlement requires coordinated national policy.','noun','B2','social',72),
('segregation','separation of groups based on race or social class','การแบ่งแยก','Segregation denies equal access to opportunities.','noun','B2','social',68),
('solidarity','unity and mutual support within a group','ความสามัคคี','Solidarity is essential to achieving collective development goals.','noun','B2','social',69),
('stereotype','an oversimplified image or belief about a group','อคติที่ตายตัว','Stereotypes limit individual potential and social progress.','noun','B2','social',70),
('urbanization','the growth and expansion of urban areas','การขยายตัวของเมือง','Rapid urbanization creates both opportunities and challenges.','noun','B2','social',72),
('inclusion','the practice of providing equal access for all people','การรวมทุกคน','Social inclusion requires removing barriers to participation.','noun','B2','social',71),
('empowerment','the process of gaining power and confidence','การเสริมพลัง','Women empowerment programs increase economic participation.','noun','B2','social',70),
('resilience','the ability to recover quickly from difficulties','ความยืดหยุ่น','Community resilience reduces the impact of natural disasters.','noun','B2','social',72),
('vulnerability','susceptibility to harm, exploitation, or hardship','ความเปราะบาง','Children in poverty face high levels of vulnerability.','noun','B2','social',70),

-- B2 — FORMAL / LAW (15 คำ)
('advocate','to publicly support or recommend a policy or cause','สนับสนุน','NGOs advocate for the rights of marginalized communities.','verb','B2','formal',71),
('amendment','a change or addition to a law or document','การแก้ไข','The constitutional amendment expanded voting rights.','noun','B2','formal',70),
('clause','a section or condition in a legal document','ข้อกำหนด','The penalty clause outlines consequences for breach.','noun','B2','formal',69),
('concede','to admit that something is true or valid','ยอมรับ','The government conceded that structural reforms were necessary.','verb','B2','formal',67),
('constitution','the fundamental laws governing a country','รัฐธรรมนูญ','The constitution guarantees freedom of expression.','noun','B2','formal',72),
('enact','to make a bill officially into law','บัญญัติกฎหมาย','Parliament enacted the new anti-corruption legislation.','verb','B2','formal',70),
('jurisdiction','the official power to make legal decisions in an area','เขตอำนาจศาล','This case falls outside the court jurisdiction.','noun','B2','formal',69),
('legislation','laws made by a government or parliament','กฎหมาย','New legislation is needed to address cybercrime effectively.','noun','B2','formal',73),
('obligation','a duty or responsibility one is required to fulfill','ภาระผูกพัน','States have a legal obligation to protect human rights.','noun','B2','formal',71),
('petition','a formal written request signed by many people','การร้องเรียน','Citizens filed a petition against the proposed development.','noun','B2','formal',68),
('precedent','an earlier event that serves as an example to follow','บรรทัดฐาน','The landmark ruling set an important legal precedent.','noun','B2','formal',70),
('ratify','to officially approve an agreement or law','ให้สัตยาบัน','The treaty was ratified by the national assembly.','verb','B2','formal',68),
('statute','a written law passed by a legislative body','กฎหมายที่บัญญัติไว้','The statute prohibits discrimination in the workplace.','noun','B2','formal',68),
('tribunal','a court or body with authority to judge disputes','ศาลพิเศษ','The case was referred to an international tribunal.','noun','B2','formal',67),
('assertion','a confident and direct statement of a fact or belief','การยืนยัน','The report contains several assertions that lack evidence.','noun','B2','formal',68),

-- B2 — IDIOM (10 คำ) — ออกสอบบ่อยใน Reading Comprehension
('at the expense of','causing harm or loss to something else','โดยแลกมาด้วยสิ่งอื่น','Growth at the expense of the environment is unsustainable.','phrase','B2','idiom',65),
('bear in mind','to remember something when making a decision','คำนึงถึง','Bear in mind that the sample size may limit generalization.','phrase','B2','idiom',68),
('bring to light','to reveal or make something publicly known','เปิดเผยให้รู้','The audit brought to light serious financial irregularities.','phrase','B2','idiom',64),
('carry out','to complete or perform a task or plan','ดำเนินการ','The committee will carry out an independent review.','phrase','B2','idiom',70),
('come to terms with','to accept a difficult or painful situation','ยอมรับกับสิ่งที่เกิดขึ้น','Society must come to terms with structural inequality.','phrase','B2','idiom',63),
('draw on','to use knowledge or experience as a resource','อ้างอิงหรือใช้ประโยชน์จาก','The policy draws on lessons from past reform efforts.','phrase','B2','idiom',65),
('give rise to','to cause something to happen or exist','ก่อให้เกิด','Inequality gives rise to social tensions and instability.','phrase','B2','idiom',67),
('in light of','taking something into consideration','เมื่อพิจารณาถึง','In light of the evidence, a policy review is warranted.','phrase','B2','idiom',68),
('on the grounds that','for the stated reason that','โดยอ้างว่า','The appeal was rejected on the grounds that it lacked evidence.','phrase','B2','idiom',65),
('take into account','to consider something when making a decision','คำนึงถึง','Policymakers must take into account the needs of all groups.','phrase','B2','idiom',69),

-- B2 — SCIENCE (5 คำ)
('algorithm','a step-by-step procedure for solving a problem','อัลกอริทึม','Machine learning algorithms detect patterns in large datasets.','noun','B2','science',72),
('correlation','a statistical relationship between two variables','ความสัมพันธ์','There is a strong correlation between education and income.','noun','B2','science',74),
('infrastructure','the basic physical systems needed by a society','โครงสร้างพื้นฐาน','Digital infrastructure is essential for a modern economy.','noun','B2','science',76),
('innovation','a new idea, method, or invention','นวัตกรรม','Technological innovation drives economic competitiveness.','noun','B2','science',78),
('simulation','a model that imitates a real-world process or system','การจำลอง','Computer simulations help predict climate change outcomes.','noun','B2','science',70),

-- =====================================================================
-- C1 — ACADEMIC (20 คำ)
-- =====================================================================
('acumen','the ability to make quick and accurate judgments','ความเฉียบแหลม','Political acumen is required to navigate complex negotiations.','noun','C1','academic',60),
('axiom','a statement regarded as self-evidently true','สัจพจน์','It is an axiom that good governance requires accountability.','noun','C1','academic',58),
('cogent','clear, logical, and convincing in argument','น่าเชื่อถือและสมเหตุสมผล','The researcher presented a cogent argument for structural reform.','adjective','C1','academic',59),
('contentious','causing or likely to cause strong disagreement','ที่เป็นที่ถกเถียง','Land reform is a contentious issue in rural politics.','adjective','C1','academic',60),
('dearth','a scarcity or insufficient supply of something','การขาดแคลน','There is a dearth of empirical research on this specific topic.','noun','C1','academic',58),
('efficacious','successful in producing the desired result','มีประสิทธิผลสูง','The intervention proved highly efficacious in reducing poverty.','adjective','C1','academic',58),
('elusive','difficult to find, achieve, or define','ยากที่จะเข้าถึง','Sustainable development remains an elusive goal for many nations.','adjective','C1','academic',59),
('enumerate','to list items one by one in a systematic way','ระบุรายการ','The report enumerates the conditions under which aid is granted.','verb','C1','academic',58),
('exacerbate','to make a problem or bad situation worse','ทำให้รุนแรงขึ้น','Poor policy implementation can exacerbate existing inequalities.','verb','C1','academic',60),
('fallacious','based on mistaken beliefs or false reasoning','ผิดพลาดและไม่มีเหตุผล','The argument was fallacious and lacked empirical support.','adjective','C1','academic',59),
('formidable','inspiring respect or fear through strength or size','น่าเกรงขาม','The challenge of eliminating poverty is formidable but achievable.','adjective','C1','academic',59),
('impede','to delay or obstruct progress or movement','ขัดขวาง','Corruption impedes economic development and investor confidence.','verb','C1','academic',61),
('incisive','intelligently analytical and clear in thinking','ตรงประเด็นและแหลมคม','An incisive analysis revealed the root causes of policy failure.','adjective','C1','academic',57),
('lucid','clearly expressed and easy to understand','ชัดเจนและเข้าใจง่าย','The professor provided a lucid explanation of complex theory.','adjective','C1','academic',59),
('manifest','clearly apparent or obvious; to show clearly','ชัดเจน','The consequences of inequality manifest in higher crime rates.','adjective','C1','academic',58),
('perspicacious','having a ready insight into things; perceptive','มีไหวพริบ','A perspicacious observer would notice the contradictions.','adjective','C1','academic',58),
('prevalent','widespread in a particular area at a given time','แพร่หลาย','Corruption is prevalent in systems lacking strong oversight.','adjective','C1','academic',60),
('probity','the quality of having strong moral principles','ความซื่อสัตย์สุจริต','Probity is essential for officials in positions of public trust.','noun','C1','academic',58),
('recalcitrant','stubbornly resistant to authority or control','ดื้อรั้น','Recalcitrant officials blocked the implementation of reforms.','adjective','C1','academic',57),
('volatile','liable to change rapidly and unpredictably','ไม่แน่นอน','Volatile political environments deter long-term foreign investment.','adjective','C1','academic',60),

-- C1 — FORMAL (20 คำ)
('approbation','official approval or praise from authority','การอนุมัติ','The proposal received approbation from the committee.','noun','C1','formal',56),
('arduous','involving or requiring great effort and endurance','ยากลำบาก','The negotiation process was arduous but ultimately successful.','adjective','C1','formal',58),
('candor','the quality of being open, frank, and honest','ความตรงไปตรงมา','Political candor is rare but essential for building trust.','noun','C1','formal',57),
('circumspect','cautious and considering all possible consequences','รอบคอบ','Officials must be circumspect before making public statements.','adjective','C1','formal',57),
('coerce','to force someone to do something through threats','บังคับ','Citizens must not be coerced into political compliance.','verb','C1','formal',59),
('compendium','a collection of detailed information about a subject','ชุดข้อมูลสมบูรณ์','The handbook serves as a compendium of governance best practices.','noun','C1','formal',56),
('deprecate','to express strong disapproval of something','ไม่เห็นด้วยอย่างรุนแรง','Experts deprecated the hasty implementation of the new law.','verb','C1','formal',57),
('diffidence','modesty or shyness resulting from lack of confidence','ความขี้อาย','His diffidence prevented him from challenging the flawed logic.','noun','C1','formal',56),
('dogma','a principle or set of beliefs held as absolutely true','หลักคำสอน','Policy should be evidence-based rather than driven by dogma.','noun','C1','formal',58),
('eminent','respected and admired within a particular field','มีชื่อเสียง','An eminent economist was appointed to lead the commission.','adjective','C1','formal',59),
('erudite','having or showing extensive knowledge or learning','มีความรู้กว้างขวาง','The erudite professor challenged conventional economic assumptions.','adjective','C1','formal',58),
('expedite','to speed up the progress or completion of something','เร่งรัด','Digitalization can expedite administrative processes significantly.','verb','C1','formal',59),
('extant','still in existence; not destroyed or lost','ที่ยังคงมีอยู่','The extant literature provides insufficient guidance on this issue.','adjective','C1','formal',57),
('grandiloquent','using pompous or inflated language to impress','โอ้อวด','The grandiloquent speech obscured the lack of policy substance.','adjective','C1','formal',49),
('immutable','unchanging over time or unable to be changed','ไม่เปลี่ยนแปลง','No principle of governance is entirely immutable.','adjective','C1','formal',51),
('laconic','using very few words to express something','สั้นกระชับ','His laconic response revealed little about the government plan.','adjective','C1','formal',51),
('mendacious','not telling the truth; characterized by deception','ชอบโกหก','Mendacious reporting undermines public trust in institutions.','adjective','C1','formal',50),
('obdurate','stubbornly refusing to change one opinion or course','ดื้อรั้น','The minister remained obdurate despite widespread public criticism.','adjective','C1','formal',50),
('reticent','reluctant to speak openly about something','ไม่ชอบแสดงความคิดเห็น','The agency was reticent about releasing the full audit report.','adjective','C1','formal',51),
('tenacious','very determined and not giving up easily','มุ่งมั่น','Tenacious advocacy by civil society led to significant reform.','adjective','C1','formal',59),

-- C1 — SOCIAL (10 คำ)
('authoritarianism','a political system with concentrated unchecked power','ลัทธิเผด็จการ','Authoritarianism erodes civil liberties and democratic norms.','noun','C1','social',58),
('disenfranchise','to deprive someone of their rights or the vote','ลิดรอนสิทธิ์','Restrictive laws can disenfranchise vulnerable communities.','verb','C1','social',58),
('meritocracy','a system where advancement is based on ability','ระบบคุณธรรม','A true meritocracy ensures equal opportunity regardless of origin.','noun','C1','social',58),
('patronage','favoritism shown to supporters in political appointments','ระบบอุปถัมภ์','Political patronage undermines merit-based public service.','noun','C1','social',58),
('philanthropy','the practice of donating to benefit the public good','การกุศล','Corporate philanthropy supplements government social spending.','noun','C1','social',59),
('polarization','the division of a group into two opposing factions','การแบ่งขั้ว','Political polarization makes consensus-building extremely difficult.','noun','C1','social',59),
('reparation','compensation made for a wrong or harm done','การชดใช้','Reparation policies aim to address historical injustices.','noun','C1','social',57),
('xenophobia','intense fear or hatred of people from other countries','การกีดกันคนต่างด้าว','Xenophobia tends to rise when economic insecurity increases.','noun','C1','social',57),
('gentrification','transformation of an area by wealthier residents','การขับไล่คนจนออกจากพื้นที่','Gentrification displaces long-term residents from urban areas.','noun','C1','social',57),
('diaspora','people who have settled far from their original homeland','คนพลัดถิ่น','Diaspora remittances contribute significantly to national income.','noun','C1','social',56),

-- =====================================================================
-- C2 — FORMAL (20 คำ)
-- =====================================================================
('abstruse','difficult to understand; obscure in meaning','ยากที่จะเข้าใจ','The legal reasoning was abstruse and inaccessible to the public.','adjective','C2','formal',50),
('acrimonious','angry and bitter in speech or manner','ขมขื่นและรุนแรง','The negotiations became acrimonious after trust collapsed.','adjective','C2','formal',51),
('anachronistic','belonging to a different time period; outdated','ผิดยุคสมัย','The law is anachronistic and fails to address digital realities.','adjective','C2','formal',50),
('apocryphal','of doubtful authenticity; widely circulated but untrue','ที่น่าสงสัยว่าเป็นความจริง','The widely cited statistic turned out to be apocryphal.','adjective','C2','formal',50),
('assiduous','showing great care, effort, and perseverance','ขยันขันแข็ง','Assiduous attention to detail prevented a major policy error.','adjective','C2','formal',51),
('attenuate','to reduce the strength, effect, or value of something','ลดทอน','The reform attenuated the power of the central bureaucracy.','verb','C2','formal',50),
('bifurcate','to divide into two branches or separate parts','แยกออกเป็นสองส่วน','Opinion on the issue tends to bifurcate along ideological lines.','verb','C2','formal',49),
('conflate','to wrongly combine two distinct ideas into one','รวมเข้าด้วยกันอย่างผิดๆ','It is a logical error to conflate correlation with causation.','verb','C2','formal',50),
('desideratum','something considered highly desirable or necessary','สิ่งที่จำเป็นอย่างยิ่ง','Equity is a desideratum of any just and functional policy system.','noun','C2','formal',48),
('didactic','intended to teach or instruct a moral lesson','ที่มีเจตนาสั่งสอน','The report adopts a didactic tone unsuitable for policymakers.','adjective','C2','formal',51),
('ebullient','cheerful and full of energy or enthusiasm','มีชีวิตชีวา','The minister remained ebullient despite criticism from opposition.','adjective','C2','formal',50),
('encomium','a formal speech or piece of writing expressing praise','คำสรรเสริญเยินยอ','The retiring official received a heartfelt encomium from peers.','noun','C2','formal',49),
('evanescent','soon passing out of sight or memory; fleeting','ที่จางหายไปเร็ว','Political goodwill is often evanescent in polarized environments.','adjective','C2','formal',50),
('forbearance','patient restraint and tolerance under provocation','ความอดกลั้น','Diplomatic forbearance prevented the dispute from escalating.','noun','C2','formal',51),
('inexorable','impossible to stop or prevent; relentless','หลีกเลี่ยงไม่ได้','The inexorable rise of automation will reshape the labor market.','adjective','C2','formal',51),
('inscrutable','impossible to understand or interpret','ลึกลับ','The official gave an inscrutable response to the press.','adjective','C2','formal',50),
('obfuscate','to make something unclear or hard to understand','ทำให้งงงวย','Political language is sometimes used to obfuscate rather than inform.','verb','C2','formal',51),
('parsimony','extreme reluctance to spend money or resources','ความตระหนี่','Fiscal parsimony during a recession can worsen unemployment.','noun','C2','formal',49),
('perfidious','guilty of betrayal or treachery','ทรยศ','Perfidious actors undermine the integrity of international agreements.','adjective','C2','formal',49),
('portentous','of great or ominous significance; self-important','มีนัยสำคัญ','The summit produced a portentous declaration on global governance.','adjective','C2','formal',49),

-- C2 — ACADEMIC (15 คำ)
('antithetical','directly opposed or contrasted to something','ตรงกันข้ามอย่างสิ้นเชิง','Unbridled growth is antithetical to sustainable development.','adjective','C2','academic',52),
('apotheosis','the highest point of development; the perfect example','จุดสูงสุด','The treaty represented the apotheosis of multilateral diplomacy.','noun','C2','academic',51),
('contiguous','sharing a common boundary; directly adjacent','ที่ติดกัน','Contiguous states must cooperate closely on border security.','adjective','C2','academic',52),
('dissonance','a tension arising from conflicting ideas or values','ความขัดแย้งภายใน','There is a cognitive dissonance between stated policy and actual action.','noun','C2','academic',52),
('exigent','pressing and requiring immediate attention or action','เร่งด่วนและจำเป็น','The exigent circumstances justified the use of emergency powers.','adjective','C2','academic',51),
('inchoate','just beginning and not yet fully formed or developed','ยังไม่สมบูรณ์','The reform agenda remains inchoate and lacks measurable targets.','adjective','C2','academic',50),
('inimical','tending to obstruct or harm something','เป็นปฏิปักษ์','Vested interests are often inimical to meaningful structural reform.','adjective','C2','academic',50),
('mendacity','the tendency to be untruthful or dishonest','การโกหกเป็นนิสัย','Institutional mendacity erodes public confidence in government.','noun','C2','academic',50),
('perspicacity','the quality of having a ready and accurate insight','ความเฉียบแหลม','Perspicacity is required to detect subtle biases in data.','noun','C2','academic',51),
('polemic','a strong verbal or written attack on an opinion','การโต้แย้งอย่างรุนแรง','The scholar published a fierce polemic against the dominant theory.','noun','C2','academic',51),
('predilection','a preference or special liking for something','ความชอบเป็นพิเศษ','The bureaucracy has a predilection for procedural compliance.','noun','C2','academic',51),
('preponderance','the quality of being greater in number or importance','ความเหนือกว่า','A preponderance of evidence supports the need for reform.','noun','C2','academic',51),
('solipsistic','excessively self-centered; failing to consider others','ที่มีศูนย์กลางเป็นตัวเอง','A solipsistic policy design ignores the needs of minority communities.','adjective','C2','academic',49),
('tendentious','promoting a particular cause in a biased way','ที่มีอคติ','The report was criticized as tendentious and politically motivated.','adjective','C2','academic',50),
('veracious','habitually speaking or representing the truth','ที่พูดความจริง','A veracious account of events requires corroborating evidence.','adjective','C2','academic',50)

ON CONFLICT (word) DO NOTHING;
